name: Build Hub Workspace

on:
  push:
    branches: ['main']
    paths:
    - image/*
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/sprint-cloud/workspace
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_CONTEXT: image
  DOCKER_BUILDKIT: 1
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Image
        id: build
        run: |-
          docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest $IMAGE_CONTEXT
      - name: Test Image
        run: |-
          docker run $IMAGE_NAME:$IMAGE_TAG sh -c 'echo Very simple test' 
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/sprint-cloud
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Push image
        run: |-
          docker push -a $IMAGE_NAME
      - name: Create Pull PR for template
        working-directory: template
        run: |-
          git checkout -b "update-image-$IMAGE_TAG"
          sed -i "s|image.=.*|image = $IMAGE_NAME:$IMAGE_TAG|" image.auto.tfvars
          git commit -am "Update Image to $IMAGE_NAME:$IMAGE_TAG"
          git push

          

        
