name: Build Workspace image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Workspace image
      working-directory: ./image
      run: docker build . --file Dockerfile --tag ghcr.io/sprint-cloud/workspace/ubuntu:$(date +%s)
    - name: Push Workspace image
      run: docker push hcr.io/sprint-cloud/workspace/ubuntu:latest
