name: Workspace CI

on:
  push:
    branches: ['main']
    paths:
    - image/*
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/sprint-cloud/workspace
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_CONTEXT: image
  DOCKER_BUILDKIT: 1
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Image
        id: build
        run: |-
          docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest $IMAGE_CONTEXT
      - name: Test Image
        run: |-
          docker run $IMAGE_NAME:$IMAGE_TAG sh -c 'echo Very simple test' 
      - name: Login to GHCR
        uses: docker/login-action@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io/sprint-cloud
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Push image
        if: ${{ github.event_name != 'pull_request' }}
        run: |-
          docker push -a $IMAGE_NAME
      - name: Create Pull PR for template
        if: ${{ github.event_name != 'pull_request' }}
        working-directory: template
        run: |-
          BRANCH="update-image-$IMAGE_TAG"
          IMAGE='"$IMAGE_NAME:$IMAGE_TAG"'
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "noreply@sprinthub.nl"
          git checkout -b $BRANCH
          sed -i "s|image.=.*|image = $IMAGE|" image.auto.tfvars
          git commit -am "[Auto Generated] Update Image to $IMAGE"
          git push --set-upstream origin $BRANCH
          gh pr create --fill

          

        
