name: Workspace CD

on:
  push:
    branches:
      - main
    paths: ['template/*']
  pull_request:
    paths: ['template/*']
  workflow_dispatch:
    

jobs:
  publish-template:
    runs-on: ubuntu-latest
    steps:
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
        tags: tag:cd

    - uses: actions/checkout@v4
      name: Checkout source code

    - name: Test
      working-directory: template
      run: |-

    
