name: Workspace CD

on:
  push:
    branches:
      - main
    paths: ['template/*']
  workflow_dispatch:
    
env:
  TEMPLATE_NAME: sprint-default-template
  TEMPLATE_DISPLAY_NAME: "Sprint Developer Template"
  TEMPLATE_DESCRIPTION: |
    Ondersteund: Docker, Python, PHP (composer), Javascript(NodeJS), C# en Golang. 
  TEMPLATE_CONTEXT: template
  
jobs:
  publish-template:
    runs-on: ubuntu-latest
    steps:
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
        tags: tag:cd
        version: 1.76.6
    - name: Setup Coder
      uses: coder/setup-action@v1
      with:
        access_url: ${{ secrets.CODER_URL }}
        coder_session_token: ${{ secrets.CODER_TOKEN }}
    - uses: actions/checkout@v4
      name: Checkout source code

    - name: Publish Template
      run: |-
        coder template push $TEMPLATE_NAME -y -d $TEMPLATE_CONTEXT -m "$(git log -1 --pretty=%B)"

    
